apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: staging
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./data/postgresql  # Ensure this path exists on your host machine or change as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: staging
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=  # "postgres" in base64
  postgres-password: cGFzc3dvcmQ=  # "password" in base64, replace this with your base64 encoded password

# To encode your password in base64, you can use the following command:
# Linux/Mac: echo -n 'your-password' | base64
# Windows: echo -n 'your-password' | openssl base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: app_db  # Adjust as needed
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: staging
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
