prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
    mountPropagation: HostToContainer

  tolerations: []

  service:
    type: ClusterIP

alertmanager:
  persistentVolume:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 2Gi

  service:
    type: ClusterIP
    port: 9093

server:
  persistentVolume:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 8Gi

  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090
